source :rubygems

# Project requirements
gem 'rake'
gem 'rack-flash'
gem 'thin' # or mongrel

# Component requirements
gem 'less'
gem 'rack-less'
gem 'erubis'
gem 'dm-sqlite-adapter'
gem 'data_mapper'

# Test requirements
gem 'shoulda', :group => "test"
gem 'rack-test', :require => "rack/test", :group => "test"


# Padrino
gem 'padrino', "0.9.18"
